const moviesList = [
    {
      id: 1,
      title: "Inception",
      description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
      posterUrl: "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
      rating: 3,
      trailer: "https://www.youtube.com/embed/YoHD9XEInc0",
    },
    {
      id: 2,
      title: "The Matrix",
      description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
      posterUrl: "https://m.media-amazon.com/images/I/51EG732BV3L._AC_.jpg",
      rating: 4,
      trailer: "https://www.youtube.com/embed/vKQi3bBA1y8",
    },
    {
      id: 3,
      title: "Interstellar",
      description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0zt0lp-O3XdL8zzdrEvyzmcl6kOwfgbv4xQ&s",
      rating: 3,
      trailer: "https://www.youtube.com/embed/zSWdZVtXT7E",
    },
    {
      id: 4,
      title: "Game of Thrones",
      description: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
      posterUrl: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781608872190/game-of-thrones-9781608872190_hr.jpg",
      rating: 5,
      trailer: "https://www.youtube.com/embed/BpJYNVhGf1s",
    },
    {
      id: 5,
      title: "Prison Break",
      description: "Due to a political conspiracy, an innocent man is sent to death row, and his only hope is his brother, who makes it his mission to deliberately get himself sent to the same prison in order to break the both of them out",
      posterUrl: "https://fr.web.img5.acsta.net/pictures/17/05/22/16/49/588696.jpg",
      rating: 5,
      trailer: "https://www.youtube.com/embed/AL9zLctDJaU",
    },
    {
      id: 6,
      title: "La Casa de Papel",
      description: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
      posterUrl: "https://fr.web.img4.acsta.net/c_310_420/pictures/21/08/02/16/08/1706767.jpg",
      rating: 4,
      trailer: "https://www.youtube.com/embed/ZAXA1DV4dtI",
    },
    {
      id: 7,
      title: "Breaking Bad",
      description: "A high school chemistry teacher turned methamphetamine producer navigates the dangers of the criminal underworld.",
      posterUrl: "https://fr.web.img5.acsta.net/pictures/19/06/18/12/11/3956503.jpg",
      rating: 5,
      trailer: "https://www.youtube.com/embed/HhesaQXLuRY",
    },
    {
      id: 8,
      title: "Stranger Things",
      description: "A group of young friends in a small town uncover a series of supernatural mysteries and government experiments.",
      posterUrl: "https://fr.web.img4.acsta.net/pictures/22/05/18/14/31/5186184.jpg",
      rating: 4,
      trailer: "https://www.youtube.com/embed/b9EkMc79ZSU",
    },
    {
      id: 11,
      title: "Avengers: Endgame",
      description: "After the devastating events of Avengers: Infinity War, the Avengers assemble once more to reverse Thanos' actions and restore balance to the universe.",
      posterUrl: "https://m.media-amazon.com/images/I/81ExhpBEbHL._AC_SY679_.jpg",
      rating: 4,
      trailer: "https://www.youtube.com/embed/TcMBFSGVi1c",
    },
    {
      id: 12,
      title: "The Dark Knight",
      description: "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
      posterUrl: "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg",
      rating: 4,
      trailer: "https://www.youtube.com/embed/EXeTwQWrcwY",
    },
    {
      id: 13,
      title: "Spider-Man: No Way Home",
      description: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.",
      posterUrl: "https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg",
      rating: 4,
      trailer: "https://www.youtube.com/embed/JfVOs4VSpmA",
    },
    {
      id: 14,
      title: "Joker",
      description: "Mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He embarks on a downward spiral that leads to the creation of his alter ego, the Joker.",
      posterUrl: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg",
      rating: 4,
      trailer: "https://www.youtube.com/embed/zAGVQLHvwOY",
    },
    {
      id: 15,
      title: "Avatar",
      description: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      posterUrl: "https://upload.wikimedia.org/wikipedia/en/d/d6/Avatar_%282009_film%29_poster.jpg",
      rating: 4,
      trailer: "https://www.youtube.com/embed/5PSNL1qE6VY",
    },
    
    {
      id: 9,
      title: "The Witcher",
      description: "Geralt of Rivia, a mutated monster-hunter for hire, journeys through a world where people often prove more wicked than beasts.",
      posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9l0qTSnfSABEG9p9ZJqMeLaqaMBQAQvyufQ&s",
      rating: 3,
      trailer: "https://www.youtube.com/embed/ndl1W4ltcmg",
    },
    {
      id: 10,
      title: "Narcos",
      description: "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar and the Medellín Cartel.",
      posterUrl: "https://fr.web.img4.acsta.net/c_310_420/pictures/15/07/29/14/33/086520.jpg",
      rating: 4,
      trailer: "https://www.youtube.com/embed/U7elNhHwgBU",
    }, ]

    export default moviesList;